###
POST http://localhost:3000/api/v1/books/book HTTP/1.1
Content-Type: application/json

{
"tittle":"cien años de soledad",
"editorial":"Editorial Sudamericana",
"back_matter":{
    "languaje":"español",
    "others":[{
        "subgenre":"Realismo mágico",
        "Formato":"impreso"
    }]
},
"author":{
    "personal_data":{
        "year_of_birth":"2015"
    },
    "author_name":"Gabriel García Márquez"
},
"motto":"El mundo habrá acabado de joderse el día en que los hombres viajen en primera clase y la literatura en el vagón de carga"
}
###

###
PUT http://localhost:3000/api/v1/books/62335dbc4a5e7a507966330c HTTP/1.1
Content-Type: application/json

{
"tittle":"El retrato de Dorian Gray",
"editorial":"Lippincott's Monthly Magazine",
"back_matter":{
    "languaje":"ingles",
    "others":[{
        "subgenre":"Novela gótica",
        "Formato":"impreso"
    }]
},
"author":{
    "personal_data":{
        "year_of_birth":"1854"
    },
    "author_name":"Oscar Wilde"
},
"motto":"La verdad es raramente pura y nunca simple"
}

###
GET  http://localhost:3000/api/v1/books HTTP/1.1

###
GET  http://localhost:3000/api/v1/books/1854 HTTP/1.1

###
DELETE  http://localhost:3000/api/v1/books/62335dbc4a5e7a507966330c HTTP/1.1